# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gigapet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gigapet
  pod 'SwiftLint'
  pod 'NetworkHandler'

  target 'GigapetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GigapetUITests' do
    # Pods for testing
  end

end
